<?php

/**
 * @file
 * Contains social_post_twitter.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * If the user has permission to associate a Twitter account, he will see a
 * table with his accounts and can add more accounts.
 */
function social_post_example_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $current_user = \Drupal::currentUser();
  // If the form is the user edit form (not user register form or others).
  // @see https://www.drupal.org/node/2854977
  if ($form_id == 'user_form') {
    // Gets the current user info.
    $current_user = \Drupal::currentUser();

    if (_social_post_example_can_grant_permission($current_user)) {
      // Add a button to authorize twitter autoposting.
      $form += _social_post_example_user_edit_form($current_user);
    }
  }
}

/**
 * Checks if the user is allowed to grant permission for autoposting.
 *
 * @param \Drupal\Core\Session\AccountInterface $current_user
 *   The current user.
 *
 * @return bool
 *   The user can or cannot allow tweeting on his behalf.
 */
function _social_post_example_can_grant_permission(AccountInterface $current_user) {
  $routeMatch = \Drupal::service('current_route_match');

  // If the current user has permission to autotwet and its id is the same as
  // the user id of parameter.
  if ($current_user->hasPermission('perform twitter autoposting tasks')
    && $current_user->id() == $routeMatch->getParameter('user')->id()) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Creates elements to the user edit form.
 *
 * @param \Drupal\Core\Session\AccountInterface $current_user
 *   The current user.
 *
 * @return array
 *   The elements to add to the user edit form.
 */
function _social_post_example_user_edit_form(AccountInterface $current_user) {
  $accounts = _social_post_example_get_accounts_by_uid($current_user->id());

  $form['social_post_example'] = [
    '#type' => 'details',
    '#title' => t('Social Post Twitter'),
    '#open' => TRUE,
  ];
  $form['social_post_example']['accounts'] = [
    '#type' => 'table',
    '#header' => [t('Screen name'), t('Operations')],
    '#empty' => t('You have not added any account yet'),
  ];

  /* @var \Drupal\social_post_example\Entity\TwitterUser $account */
  foreach ($accounts as $id => $account) {
    $form['social_post_example']['accounts'][$id]['screen_name'] = [
      '#type' => 'link',
      '#title' => '@' . $account->getScreenName(),
      '#url' => Url::fromUri('https://twitter.com/' . $account->getScreenName()),
    ];
    $form['social_post_example']['accounts'][$id]['operations'] = [
      '#type' => 'operations',
      '#links' => [],
    ];
    $form['social_post_example']['accounts'][$id]['operations']['#links']['delete'] = [
      'title' => t('Delete'),
      'url' => Url::fromRoute('entity.social_post_example_user.delete_form', ['social_post_example_user' => $id, 'user' => TRUE]),
    ];
  }

  $form['social_post_example']['button'] = [
    '#type' => 'link',
    '#title' => t("Add account"),
    '#attributes' => [
      'class' => ['button'],
    ],
    '#url' => Url::fromRoute('social_post_example.redirect_to_twitter'),
  ];

  return $form;
}

/**
 * Gets the accounts associated to the Drupal user.
 *
 * @param int $user_id
 *   The user id.
 *
 * @return \Drupal\Core\Entity\EntityInterface[]
 *   Accounts associated to the user id.
 */
function _social_post_example_get_accounts_by_uid($user_id) {
  $accounts = \Drupal::entityTypeManager()->getStorage('social_post_example_user')->loadByProperties([
    'uid' => $user_id,
  ]);

  return $accounts;
}
