<?php

/**
 * @file
 * Tweets on node creation.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function social_post_client_node_insert(Node $node) {

  // Gets the user manager to retrieve tokens for a user.
  /** @var \Drupal\social_post\User\UserManager $user_manager */
  $user_manager = \Drupal::service('social_post.user_manager');

  $user_manager->setPluginId('social_post_twitter');

  // Gets all the Twitter accounts associated to the current user.
  $accounts = $user_manager->getAccountsByUserId($user_manager->getCurrentUser());

  $tweet = [
    'status' => 'I just published ' . $node->getTitle(),
  ];

  /*
   * Media files can be attached to the tweet.
   * $img_paths = [
   *   '/path/to/image.jpg',
   * ];
   *
   * $tweet['media_paths'] => $img_paths;
   */

  // Gets instance of Social Post Twitter Network plugin.
  /** @var \Drupal\social_post_twitter\Plugin\Network\TwitterPostInterface $plugin */
  $client = \Drupal::service('plugin.network.manager')->createInstance('social_post_twitter')->getSdk();

  // Gets the twitter post manager to tweet.
  /** @var \Drupal\social_post_twitter\TwitterPostManager $post_manager */
  $post_manager = \Drupal::service('twitter_post.manager');

  /** @var \Drupal\social_post\Entity\SocialPost $account */
  foreach ($accounts as $account) {
    $access_token = json_decode($user_manager->getToken($account->getProviderUserId()), TRUE);

    $post_manager->setClient($client)
      ->setOauthToken($access_token['oauth_token'], $access_token['oauth_token_secret'])
      ->doPost($tweet);
  }

}
